# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_dlg_post_option.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(213, 194)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(10, 140, 181, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.ed_png = QtWidgets.QCheckBox(Dialog)
        self.ed_png.setGeometry(QtCore.QRect(30, 20, 161, 23))
        self.ed_png.setObjectName("ed_png")
        self.ed_GDS = QtWidgets.QCheckBox(Dialog)
        self.ed_GDS.setGeometry(QtCore.QRect(30, 50, 201, 23))
        self.ed_GDS.setObjectName("ed_GDS")
        self.ed_FFT = QtWidgets.QCheckBox(Dialog)
        self.ed_FFT.setGeometry(QtCore.QRect(30, 80, 301, 23))
        self.ed_FFT.setObjectName("ed_FFT")
        self.ed_FHT = QtWidgets.QCheckBox(Dialog)
        self.ed_FHT.setGeometry(QtCore.QRect(30, 110, 251, 23))
        self.ed_FHT.setObjectName("ed_FHT")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.ed_png.setText(_translate("Dialog", "create PNG image"))
        self.ed_GDS.setText(_translate("Dialog", "create GDS file"))
        self.ed_FFT.setText(_translate("Dialog", "create FFT"))
        self.ed_FHT.setText(_translate("Dialog", "create FHT"))
