# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_dlg_option.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OptionDialog(object):
    def setupUi(self, OptionDialog):
        OptionDialog.setObjectName("OptionDialog")
        OptionDialog.resize(453, 284)
        self.buttonBox = QtWidgets.QDialogButtonBox(OptionDialog)
        self.buttonBox.setGeometry(QtCore.QRect(100, 200, 171, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.ed_save_cvt_data = QtWidgets.QCheckBox(OptionDialog)
        self.ed_save_cvt_data.setGeometry(QtCore.QRect(10, 10, 191, 20))
        self.ed_save_cvt_data.setObjectName("ed_save_cvt_data")
        self.ed_save_rdf_data = QtWidgets.QCheckBox(OptionDialog)
        self.ed_save_rdf_data.setGeometry(QtCore.QRect(10, 70, 211, 20))
        self.ed_save_rdf_data.setObjectName("ed_save_rdf_data")
        self.ed_save_converg = QtWidgets.QCheckBox(OptionDialog)
        self.ed_save_converg.setGeometry(QtCore.QRect(10, 100, 251, 20))
        self.ed_save_converg.setObjectName("ed_save_converg")
        self.ed_each_cvt = QtWidgets.QSpinBox(OptionDialog)
        self.ed_each_cvt.setGeometry(QtCore.QRect(210, 10, 50, 20))
        self.ed_each_cvt.setMinimum(1)
        self.ed_each_cvt.setObjectName("ed_each_cvt")
        self.label = QtWidgets.QLabel(OptionDialog)
        self.label.setGeometry(QtCore.QRect(270, 10, 90, 20))
        self.label.setObjectName("label")
        self.ed_save_cvt_movie = QtWidgets.QCheckBox(OptionDialog)
        self.ed_save_cvt_movie.setGeometry(QtCore.QRect(10, 40, 151, 23))
        self.ed_save_cvt_movie.setObjectName("ed_save_cvt_movie")
        self.bt_working_dir = QtWidgets.QPushButton(OptionDialog)
        self.bt_working_dir.setGeometry(QtCore.QRect(138, 130, 121, 31))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/folder_1"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_working_dir.setIcon(icon)
        self.bt_working_dir.setObjectName("bt_working_dir")
        self.lab_working_dir = QtWidgets.QLabel(OptionDialog)
        self.lab_working_dir.setEnabled(True)
        self.lab_working_dir.setGeometry(QtCore.QRect(0, 130, 119, 31))
        self.lab_working_dir.setMinimumSize(QtCore.QSize(61, 0))
        self.lab_working_dir.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lab_working_dir.setObjectName("lab_working_dir")

        self.retranslateUi(OptionDialog)
        self.buttonBox.accepted.connect(OptionDialog.accept)
        self.buttonBox.rejected.connect(OptionDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(OptionDialog)

    def retranslateUi(self, OptionDialog):
        _translate = QtCore.QCoreApplication.translate
        OptionDialog.setWindowTitle(_translate("OptionDialog", "Save options"))
        self.ed_save_cvt_data.setText(_translate("OptionDialog", "save \"CVT\" data on each"))
        self.ed_save_rdf_data.setText(_translate("OptionDialog", "save \"RDF\" at the end"))
        self.ed_save_converg.setText(_translate("OptionDialog", "save \"Mean distance\" at the end"))
        self.label.setText(_translate("OptionDialog", "iteration(s)"))
        self.ed_save_cvt_movie.setText(_translate("OptionDialog", "create \"CVT\" movie"))
        self.bt_working_dir.setText(_translate("OptionDialog", "PushButton"))
        self.lab_working_dir.setText(_translate("OptionDialog", "Work directory:"))
import ressources
